From Stdlib Require Import Lists.List.
Import ListNotations.

(*
  PHIL-PROV-LINEAGE-CORE-001 — bounded PROV-011/012 lineage core.

  This normalized model separates semantic qualification-claim identity from
  evidence-bundle identity and contextual admission identity, then models
  qualification dependency closure as the least relation generated by
  independently accepted grounds and dependency inheritance.

  Concrete canonical serialization, Map/Set iteration, digest computation, and
  diagnostic ordering remain representation/correspondence boundaries.
*)

Definition QualificationClaimRevision := nat.
Definition QualificationEvidenceRevision := nat.
Definition QualificationAdmissionRevision := nat.
Definition QualificationInterfaceRevision := nat.
Definition QualificationPolicyRevision := nat.
Definition QualificationGroundKey := nat.

Inductive QualificationAdmissionDecision : Type :=
| QualificationAdmitted
| QualificationRejected.

Record QualificationClaimIdentity : Type := mkQualificationClaimIdentity {
  lineageClaimRevision : QualificationClaimRevision;
  lineageClaimRequiredInterface : QualificationInterfaceRevision
}.

Record QualificationEvidenceIdentity : Type := mkQualificationEvidenceIdentity {
  lineageEvidenceClaimRevision : QualificationClaimRevision;
  lineageEvidenceRevision : QualificationEvidenceRevision
}.

Record QualificationAdmissionIdentity : Type := mkQualificationAdmissionIdentity {
  lineageAdmissionClaimRevision : QualificationClaimRevision;
  lineageAdmissionEvidenceRevision : QualificationEvidenceRevision;
  lineageAdmissionRequiredInterface : QualificationInterfaceRevision;
  lineageAdmissionPolicyRevision : QualificationPolicyRevision;
  lineageAdmissionDecision : QualificationAdmissionDecision;
  lineageAdmissionRevision : QualificationAdmissionRevision
}.

Definition EvidenceBindsClaim
  (claim : QualificationClaimIdentity)
  (evidence : QualificationEvidenceIdentity) : Prop :=
  lineageEvidenceClaimRevision evidence = lineageClaimRevision claim.

Definition AdmissionBindsClaimAndEvidence
  (claim : QualificationClaimIdentity)
  (evidence : QualificationEvidenceIdentity)
  (admission : QualificationAdmissionIdentity) : Prop :=
  EvidenceBindsClaim claim evidence /\
  lineageAdmissionClaimRevision admission = lineageClaimRevision claim /\
  lineageAdmissionEvidenceRevision admission = lineageEvidenceRevision evidence /\
  lineageAdmissionRequiredInterface admission =
    lineageClaimRequiredInterface claim.

Theorem evidence_binding_requires_exact_claim_revision :
  forall claim evidence,
    EvidenceBindsClaim claim evidence ->
    lineageEvidenceClaimRevision evidence = lineageClaimRevision claim.
Proof.
  intros claim evidence Hbinds.
  exact Hbinds.
Qed.

Theorem admission_binding_requires_exact_claim_revision :
  forall claim evidence admission,
    AdmissionBindsClaimAndEvidence claim evidence admission ->
    lineageAdmissionClaimRevision admission = lineageClaimRevision claim.
Proof.
  intros claim evidence admission Hbinds.
  exact (proj1 (proj2 Hbinds)).
Qed.

Theorem admission_binding_requires_exact_evidence_revision :
  forall claim evidence admission,
    AdmissionBindsClaimAndEvidence claim evidence admission ->
    lineageAdmissionEvidenceRevision admission = lineageEvidenceRevision evidence.
Proof.
  intros claim evidence admission Hbinds.
  exact (proj1 (proj2 (proj2 Hbinds))).
Qed.

Theorem admission_binding_requires_exact_required_interface :
  forall claim evidence admission,
    AdmissionBindsClaimAndEvidence claim evidence admission ->
    lineageAdmissionRequiredInterface admission =
      lineageClaimRequiredInterface claim.
Proof.
  intros claim evidence admission Hbinds.
  exact (proj2 (proj2 (proj2 Hbinds))).
Qed.

Theorem replacing_evidence_preserves_claim_identity :
  forall claim firstEvidence secondEvidence,
    EvidenceBindsClaim claim firstEvidence ->
    EvidenceBindsClaim claim secondEvidence ->
    lineageEvidenceClaimRevision firstEvidence =
      lineageEvidenceClaimRevision secondEvidence.
Proof.
  intros claim firstEvidence secondEvidence Hfirst Hsecond.
  rewrite Hfirst, Hsecond.
  reflexivity.
Qed.

Theorem distinct_evidence_revisions_do_not_change_claim_revision :
  forall claim firstEvidence secondEvidence,
    EvidenceBindsClaim claim firstEvidence ->
    EvidenceBindsClaim claim secondEvidence ->
    lineageEvidenceRevision firstEvidence <>
      lineageEvidenceRevision secondEvidence ->
    lineageEvidenceClaimRevision firstEvidence = lineageClaimRevision claim /\
    lineageEvidenceClaimRevision secondEvidence = lineageClaimRevision claim.
Proof.
  intros claim firstEvidence secondEvidence Hfirst Hsecond _.
  split; assumption.
Qed.

Theorem admission_context_is_downstream_of_upstream_identity :
  forall claim evidence firstAdmission secondAdmission,
    AdmissionBindsClaimAndEvidence claim evidence firstAdmission ->
    AdmissionBindsClaimAndEvidence claim evidence secondAdmission ->
    lineageAdmissionClaimRevision firstAdmission =
      lineageAdmissionClaimRevision secondAdmission /\
    lineageAdmissionEvidenceRevision firstAdmission =
      lineageAdmissionEvidenceRevision secondAdmission.
Proof.
  intros claim evidence firstAdmission secondAdmission Hfirst Hsecond.
  split.
  - rewrite (admission_binding_requires_exact_claim_revision
      claim evidence firstAdmission Hfirst).
    rewrite (admission_binding_requires_exact_claim_revision
      claim evidence secondAdmission Hsecond).
    reflexivity.
  - rewrite (admission_binding_requires_exact_evidence_revision
      claim evidence firstAdmission Hfirst).
    rewrite (admission_binding_requires_exact_evidence_revision
      claim evidence secondAdmission Hsecond).
    reflexivity.
Qed.

(* PROV-012: least-fixed-point dependency grounding. *)

Definition QualificationAdmissionKnown :=
  QualificationAdmissionRevision -> Prop.
Definition QualificationAdmissionAccepted :=
  QualificationAdmissionRevision -> Prop.
Definition QualificationGroundKnown := QualificationGroundKey -> Prop.
Definition QualificationGroundAccepted := QualificationGroundKey -> Prop.
Definition QualificationGroundReferenced :=
  QualificationAdmissionRevision -> QualificationGroundKey -> Prop.
Definition QualificationDependsOn :=
  QualificationAdmissionRevision -> QualificationAdmissionRevision -> Prop.

Definition DirectAcceptedGround
  (knownGround : QualificationGroundKnown)
  (acceptedGround : QualificationGroundAccepted)
  (referencesGround : QualificationGroundReferenced)
  (admission : QualificationAdmissionRevision)
  (ground : QualificationGroundKey) : Prop :=
  referencesGround admission ground /\
  knownGround ground /\
  acceptedGround ground.

Inductive QualificationGrounded
  (directGround : QualificationAdmissionRevision -> QualificationGroundKey -> Prop)
  (dependsOn : QualificationDependsOn)
  : QualificationAdmissionRevision -> QualificationGroundKey -> Prop :=
| QualificationGroundedDirect :
    forall admission ground,
      directGround admission ground ->
      QualificationGrounded directGround dependsOn admission ground
| QualificationGroundedInherited :
    forall admission dependency ground,
      dependsOn admission dependency ->
      QualificationGrounded directGround dependsOn dependency ground ->
      QualificationGrounded directGround dependsOn admission ground.

Arguments QualificationGroundedDirect {directGround dependsOn}.
Arguments QualificationGroundedInherited {directGround dependsOn}.

Inductive QualificationReachable
  (dependsOn : QualificationDependsOn)
  (root : QualificationAdmissionRevision)
  : QualificationAdmissionRevision -> Prop :=
| QualificationReachableRoot :
    QualificationReachable dependsOn root root
| QualificationReachableDependency :
    forall admission dependency,
      QualificationReachable dependsOn root admission ->
      dependsOn admission dependency ->
      QualificationReachable dependsOn root dependency.

Arguments QualificationReachableRoot {dependsOn root}.
Arguments QualificationReachableDependency {dependsOn root}.

Definition QualificationDependencyClosure
  (acceptedAdmission : QualificationAdmissionAccepted)
  (directGround : QualificationAdmissionRevision -> QualificationGroundKey -> Prop)
  (dependsOn : QualificationDependsOn)
  (root : QualificationAdmissionRevision) : Prop :=
  forall admission,
    QualificationReachable dependsOn root admission ->
    acceptedAdmission admission /\
    exists ground, QualificationGrounded directGround dependsOn admission ground.

Theorem direct_independent_ground_closes_one_admission :
  forall directGround dependsOn admission ground,
    directGround admission ground ->
    QualificationGrounded directGround dependsOn admission ground.
Proof.
  intros directGround dependsOn admission ground Hdirect.
  apply QualificationGroundedDirect.
  exact Hdirect.
Qed.

Theorem grounded_dependency_propagates_transitively :
  forall directGround dependsOn admission dependency ground,
    dependsOn admission dependency ->
    QualificationGrounded directGround dependsOn dependency ground ->
    QualificationGrounded directGround dependsOn admission ground.
Proof.
  intros directGround dependsOn admission dependency ground Hdepends Hgrounded.
  eapply QualificationGroundedInherited.
  - exact Hdepends.
  - exact Hgrounded.
Qed.

Theorem every_grounded_admission_has_independent_ground_leaf :
  forall directGround dependsOn admission ground,
    QualificationGrounded directGround dependsOn admission ground ->
    exists leaf, directGround leaf ground.
Proof.
  intros directGround dependsOn admission ground Hgrounded.
  induction Hgrounded as
    [admission ground Hdirect |
     admission dependency ground Hdepends Hdependency IH].
  - exists admission.
    exact Hdirect.
  - destruct IH as [leaf Hleaf].
    exists leaf.
    exact Hleaf.
Qed.

Theorem cycles_cannot_self_endorse_without_independent_ground :
  forall directGround dependsOn,
    (forall admission ground, ~ directGround admission ground) ->
    forall admission ground,
      ~ QualificationGrounded directGround dependsOn admission ground.
Proof.
  intros directGround dependsOn Hnone admission ground Hgrounded.
  destruct (every_grounded_admission_has_independent_ground_leaf
    directGround dependsOn admission ground Hgrounded) as [leaf Hleaf].
  exact (Hnone leaf ground Hleaf).
Qed.

Theorem grounded_cycle_closes_conditionally :
  forall directGround dependsOn first second ground,
    directGround first ground ->
    dependsOn second first ->
    dependsOn first second ->
    QualificationGrounded directGround dependsOn first ground /\
    QualificationGrounded directGround dependsOn second ground.
Proof.
  intros directGround dependsOn first second ground Hdirect HsecondFirst _.
  split.
  - apply QualificationGroundedDirect.
    exact Hdirect.
  - eapply QualificationGroundedInherited.
    + exact HsecondFirst.
    + apply QualificationGroundedDirect.
      exact Hdirect.
Qed.

Theorem direct_ground_requires_known_accepted_ground :
  forall knownGround acceptedGround referencesGround admission ground,
    DirectAcceptedGround
      knownGround acceptedGround referencesGround admission ground ->
    knownGround ground /\ acceptedGround ground.
Proof.
  intros knownGround acceptedGround referencesGround admission ground Hdirect.
  destruct Hdirect as [_ [Hknown Haccepted]].
  split; assumption.
Qed.

Theorem root_is_reachable :
  forall dependsOn root,
    QualificationReachable dependsOn root root.
Proof.
  intros dependsOn root.
  apply QualificationReachableRoot.
Qed.

Theorem dependency_reachability_is_transitive_one_step :
  forall dependsOn root admission dependency,
    QualificationReachable dependsOn root admission ->
    dependsOn admission dependency ->
    QualificationReachable dependsOn root dependency.
Proof.
  intros dependsOn root admission dependency Hreachable Hdepends.
  eapply QualificationReachableDependency.
  - exact Hreachable.
  - exact Hdepends.
Qed.

Theorem closure_requires_every_reachable_admission_accepted :
  forall acceptedAdmission directGround dependsOn root admission,
    QualificationDependencyClosure
      acceptedAdmission directGround dependsOn root ->
    QualificationReachable dependsOn root admission ->
    acceptedAdmission admission.
Proof.
  intros acceptedAdmission directGround dependsOn root admission Hclosure Hreachable.
  exact (proj1 (Hclosure admission Hreachable)).
Qed.

Theorem closure_requires_every_reachable_admission_grounded :
  forall acceptedAdmission directGround dependsOn root admission,
    QualificationDependencyClosure
      acceptedAdmission directGround dependsOn root ->
    QualificationReachable dependsOn root admission ->
    exists ground, QualificationGrounded directGround dependsOn admission ground.
Proof.
  intros acceptedAdmission directGround dependsOn root admission Hclosure Hreachable.
  exact (proj2 (Hclosure admission Hreachable)).
Qed.

Theorem rejected_reachable_admission_prevents_closure :
  forall acceptedAdmission directGround dependsOn root rejected,
    QualificationReachable dependsOn root rejected ->
    ~ acceptedAdmission rejected ->
    ~ QualificationDependencyClosure
        acceptedAdmission directGround dependsOn root.
Proof.
  intros acceptedAdmission directGround dependsOn root rejected Hreachable Hrejected Hclosure.
  apply Hrejected.
  eapply closure_requires_every_reachable_admission_accepted.
  - exact Hclosure.
  - exact Hreachable.
Qed.

Theorem multiple_independent_grounds_are_preserved_at_root :
  forall directGround dependsOn root dependency firstGround secondGround,
    directGround root firstGround ->
    dependsOn root dependency ->
    directGround dependency secondGround ->
    QualificationGrounded directGround dependsOn root firstGround /\
    QualificationGrounded directGround dependsOn root secondGround.
Proof.
  intros directGround dependsOn root dependency firstGround secondGround
    Hroot Hdepends Hdependency.
  split.
  - apply QualificationGroundedDirect.
    exact Hroot.
  - eapply QualificationGroundedInherited.
    + exact Hdepends.
    + apply QualificationGroundedDirect.
      exact Hdependency.
Qed.
