From Stdlib Require Import Lists.List Strings.String.
Import ListNotations.
Open Scope string_scope.

(* GENERATED FILE. DO NOT EDIT.
   Source: grammar/phase1-surface.ebnf
   Source SHA-256: 9adaec15187c2b390bf8b22bd92f4c623ff2c06861b23202de05eb2a459d55e7
   Regenerate with: python3 scripts/derive_phase1_surface_grammar.py --write

   This is the mechanically derived plain-BNF representation of the
   canonical Phase 1 concrete grammar.  Semantic acceptance remains
   governed by the checked Phil declaration/Core contracts. *)

Inductive GrammarSymbol : Type :=
| TerminalLiteral : string -> GrammarSymbol
| TerminalClass : string -> GrammarSymbol
| Nonterminal : string -> GrammarSymbol.

Definition Production : Type := (string * list GrammarSymbol)%type.

Definition phase1_surface_grammar_source_sha256 : string := "9adaec15187c2b390bf8b22bd92f4c623ff2c06861b23202de05eb2a459d55e7".
Definition phase1_surface_start : string := "source_file".

Definition phase1_surface_keywords : list string :=
  ["Bool"; "Bytes"; "Frame"; "Message"; "Nat"; "Proof"; "Session"; "Type"; "Unit"; "Validated"; "accept"; "and"; "architecture"; "as"; "assume"; "assumes"; "at"; "authority"; "bind"; "borrow"; "borrows"; "boundary"; "break"; "callable"; "callee"; "canonical"; "capability"; "captures"; "claim"; "close"; "closure"; "commit_receive"; "component"; "constraint"; "construct"; "consume"; "consumes"; "continue"; "correspondence"; "cost"; "data"; "decide"; "effects"; "else"; "end"; "ensures"; "entry"; "export"; "fail"; "failure"; "false"; "fn"; "from"; "grant"; "if"; "implementation"; "import"; "instance"; "instantiate"; "invariant"; "join"; "law"; "let"; "lifecycle"; "loop"; "match"; "module"; "not"; "obligation"; "observable"; "offer"; "on"; "opaque"; "operation"; "or"; "originates"; "outcomes"; "permits"; "preserve"; "program"; "proposition"; "protocol"; "prove"; "provider"; "provides"; "receive"; "receive_exact"; "receive_frame"; "recognize"; "record"; "recursive"; "ref"; "reject"; "release"; "replace"; "requires"; "return"; "role"; "satisfies"; "select"; "send"; "send_exact"; "state"; "structural"; "then"; "to"; "true"; "type"; "unit"; "using"; "validate"; "when"; "within"].

Definition phase1_surface_productions : list Production := [
  ("source_file", [Nonterminal "__source_file_opt_0001"; Nonterminal "__source_file_star_0002"; Nonterminal "__source_file_star_0003"]);
  ("module_decl", [TerminalLiteral "module"; Nonterminal "qualified_name"; TerminalLiteral ";"]);
  ("import_decl", [TerminalLiteral "import"; Nonterminal "qualified_name"; Nonterminal "__import_decl_opt_0004"; TerminalLiteral ";"]);
  ("top_level_decl", [Nonterminal "__top_level_decl_star_0005"; Nonterminal "declaration"]);
  ("attribute", [TerminalLiteral "@"; Nonterminal "identifier"; TerminalLiteral "("; Nonterminal "string_literal"; TerminalLiteral ")"]);
  ("declaration", [Nonterminal "record_decl"]);
  ("declaration", [Nonterminal "data_decl"]);
  ("declaration", [Nonterminal "type_alias_decl"]);
  ("declaration", [Nonterminal "claim_decl"]);
  ("declaration", [Nonterminal "callable_contract_decl"]);
  ("declaration", [Nonterminal "function_decl"]);
  ("declaration", [Nonterminal "provider_contract_decl"]);
  ("declaration", [Nonterminal "provider_implementation_decl"]);
  ("declaration", [Nonterminal "opaque_provider_implementation_decl"]);
  ("declaration", [Nonterminal "protocol_decl"]);
  ("declaration", [Nonterminal "capability_decl"]);
  ("declaration", [Nonterminal "boundary_decl"]);
  ("declaration", [Nonterminal "architecture_decl"]);
  ("declaration", [Nonterminal "component_decl"]);
  ("declaration", [Nonterminal "program_decl"]);
  ("qualified_name", [Nonterminal "identifier"; Nonterminal "__qualified_name_star_0006"]);
  ("identifier_list", [Nonterminal "identifier"; Nonterminal "__identifier_list_star_0007"]);
  ("identifier", [TerminalClass "IDENTIFIER"]);
  ("integer_literal", [TerminalClass "DECIMAL_INTEGER"]);
  ("uint_type", [TerminalClass "UINT_TYPE"]);
  ("string_literal", [TerminalClass "STRING_LITERAL"]);
  ("generic_params", [TerminalLiteral "["; Nonterminal "generic_param"; Nonterminal "__generic_params_star_0008"; TerminalLiteral "]"]);
  ("generic_param", [Nonterminal "identifier"; TerminalLiteral ":"; Nonterminal "generic_kind"]);
  ("generic_kind", [TerminalLiteral "Type"]);
  ("generic_kind", [TerminalLiteral "Nat"]);
  ("generic_kind", [TerminalLiteral "Session"]);
  ("generic_kind", [TerminalLiteral "Message"]);
  ("generic_kind", [TerminalLiteral "provider"; Nonterminal "type_expression"]);
  ("generic_kind", [TerminalLiteral "callable"; Nonterminal "type_expression"]);
  ("generic_kind", [TerminalLiteral "boundary"; Nonterminal "type_expression"]);
  ("generic_kind", [TerminalLiteral "architecture"; Nonterminal "type_expression"]);
  ("generic_requirements", [TerminalLiteral "requires"; TerminalLiteral "{"; Nonterminal "__generic_requirements_star_0009"; TerminalLiteral "}"]);
  ("generic_requirement", [TerminalLiteral "structural"; Nonterminal "identifier"; TerminalLiteral ":"; Nonterminal "identifier"; TerminalLiteral ";"]);
  ("generic_requirement", [TerminalLiteral "proposition"; Nonterminal "proposition"; TerminalLiteral ";"]);
  ("generic_requirement", [TerminalLiteral "provider"; Nonterminal "identifier"; TerminalLiteral ":"; Nonterminal "type_expression"; TerminalLiteral ";"]);
  ("generic_requirement", [TerminalLiteral "callable"; Nonterminal "identifier"; TerminalLiteral ":"; Nonterminal "type_expression"; TerminalLiteral ";"]);
  ("generic_requirement", [TerminalLiteral "boundary"; Nonterminal "identifier"; TerminalLiteral ":"; Nonterminal "type_expression"; TerminalLiteral ";"]);
  ("generic_requirement", [TerminalLiteral "architecture"; Nonterminal "identifier"; TerminalLiteral ":"; Nonterminal "type_expression"; TerminalLiteral ";"]);
  ("term_params", [TerminalLiteral "("; Nonterminal "__term_params_opt_0011"; TerminalLiteral ")"]);
  ("term_param", [Nonterminal "identifier"; TerminalLiteral ":"; Nonterminal "type_expression"]);
  ("type_expression", [TerminalLiteral "Unit"]);
  ("type_expression", [TerminalLiteral "Bool"]);
  ("type_expression", [Nonterminal "uint_type"]);
  ("type_expression", [TerminalLiteral "Bytes"; TerminalLiteral "["; Nonterminal "expression"; TerminalLiteral "]"]);
  ("type_expression", [TerminalLiteral "Frame"; TerminalLiteral "["; Nonterminal "qualified_name"; TerminalLiteral "]"]);
  ("type_expression", [TerminalLiteral "Proof"; TerminalLiteral "["; Nonterminal "proposition"; TerminalLiteral "]"]);
  ("type_expression", [TerminalLiteral "Validated"; TerminalLiteral "["; Nonterminal "qualified_name"; TerminalLiteral ","; Nonterminal "expression"; TerminalLiteral ","; Nonterminal "expression"; TerminalLiteral "]"]);
  ("type_expression", [Nonterminal "named_type"]);
  ("named_type", [Nonterminal "qualified_name"; Nonterminal "__named_type_opt_0012"]);
  ("static_arguments", [TerminalLiteral "["; Nonterminal "__static_arguments_opt_0014"; TerminalLiteral "]"]);
  ("term_arguments", [TerminalLiteral "("; Nonterminal "__term_arguments_opt_0016"; TerminalLiteral ")"]);
  ("record_decl", [TerminalLiteral "record"; Nonterminal "identifier"; Nonterminal "__record_decl_opt_0017"; Nonterminal "__record_decl_opt_0018"; TerminalLiteral "{"; Nonterminal "__record_decl_opt_0021"; TerminalLiteral "}"]);
  ("field_decl", [Nonterminal "identifier"; TerminalLiteral ":"; Nonterminal "type_expression"]);
  ("data_decl", [TerminalLiteral "data"; Nonterminal "identifier"; Nonterminal "__data_decl_opt_0022"; Nonterminal "__data_decl_opt_0023"; TerminalLiteral "="; Nonterminal "variant_decl"; Nonterminal "__data_decl_star_0024"; TerminalLiteral ";"]);
  ("variant_decl", [Nonterminal "identifier"; Nonterminal "__variant_decl_opt_0025"]);
  ("variant_payload", [TerminalLiteral "{"; Nonterminal "__variant_payload_opt_0028"; TerminalLiteral "}"]);
  ("variant_payload", [TerminalLiteral "("; Nonterminal "__variant_payload_opt_0030"; TerminalLiteral ")"]);
  ("type_alias_decl", [TerminalLiteral "type"; Nonterminal "identifier"; Nonterminal "__type_alias_decl_opt_0031"; Nonterminal "__type_alias_decl_opt_0032"; TerminalLiteral "="; Nonterminal "type_expression"; TerminalLiteral ";"]);
  ("claim_decl", [TerminalLiteral "claim"; Nonterminal "identifier"; Nonterminal "__claim_decl_opt_0033"; Nonterminal "__claim_decl_opt_0034"; Nonterminal "__claim_decl_opt_0035"; Nonterminal "__claim_decl_opt_0036"; TerminalLiteral ";"]);
  ("callable_contract_decl", [TerminalLiteral "callable"; Nonterminal "identifier"; Nonterminal "__callable_contract_decl_opt_0037"; Nonterminal "__callable_contract_decl_opt_0038"; Nonterminal "term_params"; TerminalLiteral "->"; Nonterminal "type_expression"; Nonterminal "callable_contract_block"]);
  ("callable_contract_block", [TerminalLiteral "{"; Nonterminal "__callable_contract_block_star_0039"; TerminalLiteral "}"]);
  ("callable_clause", [TerminalLiteral "requires"; Nonterminal "proposition"; TerminalLiteral ";"]);
  ("callable_clause", [TerminalLiteral "consumes"; Nonterminal "name_set"; TerminalLiteral ";"]);
  ("callable_clause", [TerminalLiteral "borrows"; Nonterminal "name_set"; TerminalLiteral ";"]);
  ("callable_clause", [TerminalLiteral "authority"; Nonterminal "type_set"; TerminalLiteral ";"]);
  ("callable_clause", [TerminalLiteral "effects"; Nonterminal "name_set"; TerminalLiteral ";"]);
  ("callable_clause", [TerminalLiteral "outcomes"; Nonterminal "type_set"; TerminalLiteral ";"]);
  ("callable_clause", [TerminalLiteral "ensures"; Nonterminal "proposition"; TerminalLiteral ";"]);
  ("callable_clause", [TerminalLiteral "assumes"; Nonterminal "proposition"; TerminalLiteral ";"]);
  ("callable_clause", [TerminalLiteral "cost"; Nonterminal "expression"; TerminalLiteral ";"]);
  ("callable_clause", [TerminalLiteral "callee"; Nonterminal "callee_transition"; TerminalLiteral ";"]);
  ("callee_transition", [TerminalLiteral "preserve"]);
  ("callee_transition", [TerminalLiteral "consume"]);
  ("callee_transition", [TerminalLiteral "replace"]);
  ("name_set", [TerminalLiteral "{"; Nonterminal "__name_set_opt_0041"; TerminalLiteral "}"]);
  ("type_set", [TerminalLiteral "{"; Nonterminal "__type_set_opt_0043"; TerminalLiteral "}"]);
  ("function_decl", [Nonterminal "__function_decl_opt_0044"; TerminalLiteral "fn"; Nonterminal "identifier"; Nonterminal "__function_decl_opt_0045"; Nonterminal "__function_decl_opt_0046"; Nonterminal "term_params"; Nonterminal "__function_decl_opt_0047"; TerminalLiteral "satisfies"; Nonterminal "type_expression"; Nonterminal "block"]);
  ("provider_contract_decl", [TerminalLiteral "provider"; Nonterminal "identifier"; Nonterminal "__provider_contract_decl_opt_0048"; Nonterminal "__provider_contract_decl_opt_0049"; TerminalLiteral "{"; Nonterminal "__provider_contract_decl_star_0050"; TerminalLiteral "}"]);
  ("provider_contract_item", [TerminalLiteral "operation"; Nonterminal "identifier"; TerminalLiteral ":"; Nonterminal "type_expression"; TerminalLiteral ";"]);
  ("provider_contract_item", [TerminalLiteral "law"; Nonterminal "identifier"; TerminalLiteral ":"; Nonterminal "proposition"; TerminalLiteral ";"]);
  ("provider_contract_item", [TerminalLiteral "lifecycle"; Nonterminal "identifier"; TerminalLiteral ":"; Nonterminal "proposition"; TerminalLiteral ";"]);
  ("provider_implementation_decl", [TerminalLiteral "provider"; TerminalLiteral "implementation"; Nonterminal "identifier"; Nonterminal "__provider_implementation_decl_opt_0051"; Nonterminal "__provider_implementation_decl_opt_0052"; TerminalLiteral "satisfies"; Nonterminal "type_expression"; TerminalLiteral "{"; Nonterminal "__provider_implementation_decl_star_0053"; TerminalLiteral "}"]);
  ("provider_implementation_item", [TerminalLiteral "operation"; Nonterminal "identifier"; TerminalLiteral "satisfies"; Nonterminal "type_expression"; Nonterminal "block"]);
  ("provider_implementation_item", [TerminalLiteral "law"; Nonterminal "identifier"; TerminalLiteral "="; Nonterminal "proposition"; TerminalLiteral ";"]);
  ("provider_implementation_item", [TerminalLiteral "lifecycle"; Nonterminal "identifier"; TerminalLiteral "="; Nonterminal "proposition"; TerminalLiteral ";"]);
  ("opaque_provider_implementation_decl", [TerminalLiteral "opaque"; TerminalLiteral "provider"; TerminalLiteral "implementation"; Nonterminal "identifier"; Nonterminal "__opaque_provider_implementation_decl_opt_0054"; Nonterminal "__opaque_provider_implementation_decl_opt_0055"; TerminalLiteral "satisfies"; Nonterminal "type_expression"; TerminalLiteral ";"]);
  ("protocol_decl", [TerminalLiteral "protocol"; Nonterminal "identifier"; Nonterminal "__protocol_decl_opt_0056"; Nonterminal "__protocol_decl_opt_0057"; TerminalLiteral "{"; Nonterminal "role_session_decl"; Nonterminal "role_session_decl"; TerminalLiteral "}"]);
  ("role_session_decl", [TerminalLiteral "role"; Nonterminal "identifier"; TerminalLiteral "="; Nonterminal "session_expression"; TerminalLiteral ";"]);
  ("session_expression", [TerminalLiteral "send"; TerminalLiteral "("; Nonterminal "term_param"; TerminalLiteral ")"; Nonterminal "__session_expression_opt_0058"; Nonterminal "__session_expression_opt_0059"; TerminalLiteral "then"; Nonterminal "session_expression"]);
  ("session_expression", [TerminalLiteral "receive"; TerminalLiteral "("; Nonterminal "term_param"; TerminalLiteral ")"; Nonterminal "__session_expression_opt_0060"; Nonterminal "__session_expression_opt_0061"; TerminalLiteral "then"; Nonterminal "session_expression"]);
  ("session_expression", [TerminalLiteral "select"; TerminalLiteral "{"; Nonterminal "session_branch"; Nonterminal "__session_expression_star_0062"; TerminalLiteral "}"]);
  ("session_expression", [TerminalLiteral "offer"; TerminalLiteral "{"; Nonterminal "session_branch"; Nonterminal "__session_expression_star_0063"; TerminalLiteral "}"]);
  ("session_expression", [TerminalLiteral "end"; Nonterminal "identifier"]);
  ("session_expression", [TerminalLiteral "recursive"; Nonterminal "identifier"; TerminalLiteral "="; Nonterminal "session_expression"]);
  ("session_expression", [TerminalLiteral "continue"; Nonterminal "identifier"]);
  ("session_branch", [Nonterminal "identifier"; Nonterminal "__session_branch_opt_0065"; Nonterminal "__session_branch_opt_0066"; Nonterminal "__session_branch_opt_0067"; TerminalLiteral "=>"; Nonterminal "session_expression"]);
  ("capability_decl", [TerminalLiteral "capability"; Nonterminal "identifier"; Nonterminal "__capability_decl_opt_0068"; Nonterminal "__capability_decl_opt_0069"; TerminalLiteral "{"; Nonterminal "__capability_decl_star_0070"; TerminalLiteral "}"]);
  ("capability_item", [TerminalLiteral "permits"; Nonterminal "qualified_name"; TerminalLiteral ";"]);
  ("capability_item", [TerminalLiteral "requires"; Nonterminal "proposition"; TerminalLiteral ";"]);
  ("capability_item", [TerminalLiteral "law"; Nonterminal "identifier"; TerminalLiteral ":"; Nonterminal "proposition"; TerminalLiteral ";"]);
  ("boundary_decl", [TerminalLiteral "boundary"; Nonterminal "identifier"; Nonterminal "__boundary_decl_opt_0071"; Nonterminal "__boundary_decl_opt_0072"; TerminalLiteral ":"; Nonterminal "type_expression"; TerminalLiteral "{"; Nonterminal "__boundary_decl_star_0073"; TerminalLiteral "}"]);
  ("boundary_item", [TerminalLiteral "receive"; TerminalLiteral "using"; Nonterminal "qualified_name"; TerminalLiteral ";"]);
  ("boundary_item", [TerminalLiteral "send"; TerminalLiteral "using"; Nonterminal "qualified_name"; TerminalLiteral ";"]);
  ("boundary_item", [TerminalLiteral "correspondence"; Nonterminal "proposition"; TerminalLiteral ";"]);
  ("boundary_item", [TerminalLiteral "canonical"; TerminalLiteral ";"]);
  ("boundary_item", [TerminalLiteral "failure"; Nonterminal "type_expression"; TerminalLiteral ";"]);
  ("boundary_item", [TerminalLiteral "law"; Nonterminal "identifier"; TerminalLiteral ":"; Nonterminal "proposition"; TerminalLiteral ";"]);
  ("architecture_decl", [TerminalLiteral "architecture"; Nonterminal "identifier"; Nonterminal "__architecture_decl_opt_0074"; Nonterminal "__architecture_decl_opt_0075"; TerminalLiteral "{"; Nonterminal "__architecture_decl_star_0076"; TerminalLiteral "}"]);
  ("architecture_item", [TerminalLiteral "instance"; Nonterminal "identifier"; TerminalLiteral "="; Nonterminal "static_reference"; TerminalLiteral ";"]);
  ("architecture_item", [TerminalLiteral "ref"; Nonterminal "identifier"; TerminalLiteral "="; Nonterminal "qualified_name"; TerminalLiteral ";"]);
  ("architecture_item", [TerminalLiteral "protocol"; Nonterminal "identifier"; TerminalLiteral "="; Nonterminal "static_reference"; TerminalLiteral ";"]);
  ("architecture_item", [TerminalLiteral "role"; Nonterminal "qualified_name"; TerminalLiteral "="; Nonterminal "qualified_name"; TerminalLiteral ";"]);
  ("architecture_item", [TerminalLiteral "bind"; Nonterminal "qualified_name"; TerminalLiteral "="; Nonterminal "qualified_name"; TerminalLiteral ";"]);
  ("architecture_item", [TerminalLiteral "authority"; Nonterminal "identifier"; TerminalLiteral ":"; Nonterminal "type_expression"; TerminalLiteral "originates"; TerminalLiteral "at"; Nonterminal "qualified_name"; TerminalLiteral ";"]);
  ("architecture_item", [TerminalLiteral "grant"; Nonterminal "qualified_name"; TerminalLiteral "="; Nonterminal "expression"; TerminalLiteral ";"]);
  ("architecture_item", [TerminalLiteral "boundary"; Nonterminal "qualified_name"; TerminalLiteral "="; Nonterminal "qualified_name"; TerminalLiteral ";"]);
  ("architecture_item", [TerminalLiteral "entry"; Nonterminal "identifier"; TerminalLiteral ":"; Nonterminal "type_expression"; TerminalLiteral ";"]);
  ("architecture_item", [TerminalLiteral "assume"; Nonterminal "proposition"; TerminalLiteral "within"; Nonterminal "qualified_name"; TerminalLiteral ";"]);
  ("architecture_item", [TerminalLiteral "export"; TerminalLiteral "obligation"; Nonterminal "qualified_name"; TerminalLiteral "to"; Nonterminal "qualified_name"; TerminalLiteral ";"]);
  ("architecture_item", [TerminalLiteral "observable"; Nonterminal "qualified_name"; TerminalLiteral ";"]);
  ("architecture_item", [TerminalLiteral "constraint"; Nonterminal "proposition"; TerminalLiteral ";"]);
  ("static_reference", [Nonterminal "qualified_name"; Nonterminal "__static_reference_opt_0077"]);
  ("component_decl", [TerminalLiteral "component"; Nonterminal "identifier"; Nonterminal "__component_decl_opt_0078"; Nonterminal "__component_decl_opt_0079"; Nonterminal "__component_decl_opt_0080"; Nonterminal "__component_decl_opt_0081"; Nonterminal "block"]);
  ("program_decl", [TerminalLiteral "program"; Nonterminal "identifier"; TerminalLiteral "="; TerminalLiteral "instantiate"; Nonterminal "static_reference"; Nonterminal "__program_decl_opt_0082"; TerminalLiteral ";"]);
  ("program_block", [TerminalLiteral "{"; Nonterminal "__program_block_star_0083"; TerminalLiteral "}"]);
  ("program_item", [TerminalLiteral "entry"; Nonterminal "identifier"; TerminalLiteral ":"; Nonterminal "type_expression"; TerminalLiteral ";"]);
  ("program_item", [TerminalLiteral "assume"; Nonterminal "proposition"; TerminalLiteral "within"; Nonterminal "qualified_name"; TerminalLiteral ";"]);
  ("program_item", [TerminalLiteral "export"; TerminalLiteral "obligation"; Nonterminal "qualified_name"; TerminalLiteral "to"; Nonterminal "qualified_name"; TerminalLiteral ";"]);
  ("program_item", [TerminalLiteral "observable"; Nonterminal "qualified_name"; TerminalLiteral ";"]);
  ("block", [TerminalLiteral "{"; Nonterminal "__block_star_0084"; TerminalLiteral "}"]);
  ("statement", [TerminalLiteral "let"; Nonterminal "pattern"; TerminalLiteral "="; Nonterminal "expression"]);
  ("statement", [TerminalLiteral "return"; Nonterminal "expression"]);
  ("statement", [Nonterminal "expression"]);
  ("pattern", [Nonterminal "identifier"]);
  ("pattern", [Nonterminal "tuple_pattern"]);
  ("pattern", [Nonterminal "record_pattern"]);
  ("tuple_pattern", [TerminalLiteral "("; Nonterminal "pattern"; TerminalLiteral ","; Nonterminal "pattern"; Nonterminal "__tuple_pattern_star_0085"; TerminalLiteral ")"]);
  ("record_pattern", [Nonterminal "qualified_name"; TerminalLiteral "{"; Nonterminal "field_pattern"; Nonterminal "__record_pattern_star_0086"; Nonterminal "__record_pattern_opt_0087"; TerminalLiteral "}"]);
  ("field_pattern", [Nonterminal "identifier"; Nonterminal "__field_pattern_opt_0088"]);
  ("expression", [Nonterminal "additive_expression"; Nonterminal "__expression_opt_0089"]);
  ("fallback", [TerminalLiteral "fail"; Nonterminal "qualified_name"]);
  ("fallback", [TerminalLiteral "reject"; Nonterminal "additive_expression"]);
  ("additive_expression", [Nonterminal "multiplicative_expression"; Nonterminal "__additive_expression_star_0090"]);
  ("multiplicative_expression", [Nonterminal "postfix_expression"; Nonterminal "__multiplicative_expression_star_0091"]);
  ("postfix_expression", [Nonterminal "primary_expression"; Nonterminal "__postfix_expression_star_0092"]);
  ("primary_expression", [Nonterminal "construct_expression"]);
  ("primary_expression", [Nonterminal "borrow_expression"]);
  ("primary_expression", [Nonterminal "if_expression"]);
  ("primary_expression", [Nonterminal "match_expression"]);
  ("primary_expression", [Nonterminal "decide_expression"]);
  ("primary_expression", [Nonterminal "closure_expression"]);
  ("primary_expression", [Nonterminal "loop_expression"]);
  ("primary_expression", [Nonterminal "continue_expression"]);
  ("primary_expression", [Nonterminal "break_expression"]);
  ("primary_expression", [Nonterminal "receive_frame_expression"]);
  ("primary_expression", [Nonterminal "receive_exact_expression"]);
  ("primary_expression", [Nonterminal "receive_expression"]);
  ("primary_expression", [Nonterminal "recognize_expression"]);
  ("primary_expression", [Nonterminal "validate_expression"]);
  ("primary_expression", [Nonterminal "send_exact_expression"]);
  ("primary_expression", [Nonterminal "send_expression"]);
  ("primary_expression", [Nonterminal "select_expression"]);
  ("primary_expression", [Nonterminal "commit_receive_expression"]);
  ("primary_expression", [Nonterminal "fail_expression"]);
  ("primary_expression", [Nonterminal "close_expression"]);
  ("primary_expression", [Nonterminal "release_expression"]);
  ("primary_expression", [Nonterminal "accept_expression"]);
  ("primary_expression", [Nonterminal "prove_expression"]);
  ("primary_expression", [Nonterminal "parenthesized_expression"]);
  ("primary_expression", [TerminalLiteral "true"]);
  ("primary_expression", [TerminalLiteral "false"]);
  ("primary_expression", [TerminalLiteral "unit"]);
  ("primary_expression", [Nonterminal "integer_literal"]);
  ("primary_expression", [Nonterminal "name_expression"]);
  ("name_expression", [Nonterminal "qualified_name"; Nonterminal "__name_expression_opt_0093"; Nonterminal "__name_expression_opt_0094"]);
  ("construct_expression", [TerminalLiteral "construct"; Nonterminal "qualified_name"; TerminalLiteral "{"; Nonterminal "__construct_expression_opt_0097"; TerminalLiteral "}"]);
  ("field_assignment", [Nonterminal "identifier"; TerminalLiteral "="; Nonterminal "expression"]);
  ("borrow_expression", [TerminalLiteral "borrow"; Nonterminal "additive_expression"; TerminalLiteral "as"; Nonterminal "identifier"; Nonterminal "block"]);
  ("join_clause", [TerminalLiteral "join"; TerminalLiteral "state"; TerminalLiteral "("; Nonterminal "__join_clause_opt_0099"; TerminalLiteral ")"]);
  ("state_slot", [Nonterminal "identifier"; TerminalLiteral ":"; Nonterminal "type_expression"]);
  ("if_expression", [TerminalLiteral "if"; Nonterminal "expression"; Nonterminal "__if_expression_opt_0100"; Nonterminal "block"; Nonterminal "__if_expression_opt_0101"]);
  ("match_expression", [TerminalLiteral "match"; Nonterminal "expression"; Nonterminal "__match_expression_opt_0102"; TerminalLiteral "{"; Nonterminal "match_arm"; Nonterminal "__match_expression_star_0103"; TerminalLiteral "}"]);
  ("match_arm", [Nonterminal "case_pattern"; TerminalLiteral "=>"; Nonterminal "block"]);
  ("match_arm", [Nonterminal "case_pattern"; TerminalLiteral "=>"; Nonterminal "statement"]);
  ("case_pattern", [Nonterminal "qualified_name"; Nonterminal "__case_pattern_opt_0107"]);
  ("field_binder", [Nonterminal "identifier"; Nonterminal "__field_binder_opt_0108"]);
  ("decide_expression", [TerminalLiteral "decide"; Nonterminal "additive_expression"; TerminalLiteral "{"; Nonterminal "match_arm"; Nonterminal "__decide_expression_star_0109"; TerminalLiteral "}"]);
  ("closure_expression", [TerminalLiteral "closure"; Nonterminal "term_params"; TerminalLiteral "satisfies"; Nonterminal "type_expression"; Nonterminal "__closure_expression_opt_0111"; Nonterminal "block"]);
  ("loop_expression", [TerminalLiteral "loop"; Nonterminal "__loop_expression_opt_0113"; Nonterminal "__loop_expression_opt_0114"; Nonterminal "block"]);
  ("state_binding", [Nonterminal "identifier"; TerminalLiteral "="; Nonterminal "expression"]);
  ("continue_expression", [TerminalLiteral "continue"; Nonterminal "__continue_expression_opt_0117"]);
  ("break_expression", [TerminalLiteral "break"; Nonterminal "__break_expression_opt_0120"]);
  ("receive_frame_expression", [TerminalLiteral "receive_frame"; TerminalLiteral "("; Nonterminal "expression"; TerminalLiteral ")"]);
  ("receive_exact_expression", [TerminalLiteral "receive_exact"; Nonterminal "additive_expression"; TerminalLiteral "on"; Nonterminal "additive_expression"; Nonterminal "__receive_exact_expression_opt_0121"]);
  ("receive_expression", [TerminalLiteral "receive"; Nonterminal "type_expression"; TerminalLiteral "on"; Nonterminal "additive_expression"]);
  ("recognize_expression", [TerminalLiteral "recognize"; Nonterminal "qualified_name"; TerminalLiteral "from"; Nonterminal "additive_expression"]);
  ("validate_expression", [TerminalLiteral "validate"; Nonterminal "qualified_name"; Nonterminal "__validate_expression_opt_0122"; TerminalLiteral "on"; Nonterminal "additive_expression"]);
  ("send_exact_expression", [TerminalLiteral "send_exact"; Nonterminal "additive_expression"; TerminalLiteral "on"; Nonterminal "additive_expression"]);
  ("send_expression", [TerminalLiteral "send"; Nonterminal "additive_expression"; TerminalLiteral "on"; Nonterminal "additive_expression"]);
  ("select_expression", [TerminalLiteral "select"; Nonterminal "branch_value"; TerminalLiteral "on"; Nonterminal "additive_expression"; Nonterminal "__select_expression_opt_0123"]);
  ("branch_value", [Nonterminal "qualified_name"; Nonterminal "__branch_value_opt_0124"]);
  ("commit_receive_expression", [TerminalLiteral "commit_receive"; Nonterminal "additive_expression"; TerminalLiteral "using"; Nonterminal "additive_expression"]);
  ("fail_expression", [TerminalLiteral "fail"; Nonterminal "failure_target"; TerminalLiteral "on"; Nonterminal "additive_expression"]);
  ("failure_target", [Nonterminal "qualified_name"; Nonterminal "__failure_target_opt_0125"]);
  ("close_expression", [TerminalLiteral "close"; Nonterminal "additive_expression"]);
  ("release_expression", [TerminalLiteral "release"; Nonterminal "additive_expression"]);
  ("accept_expression", [TerminalLiteral "accept"; Nonterminal "additive_expression"; TerminalLiteral "as"; Nonterminal "type_expression"]);
  ("prove_expression", [TerminalLiteral "prove"; Nonterminal "proposition"]);
  ("parenthesized_expression", [TerminalLiteral "("; Nonterminal "__parenthesized_expression_opt_0127"; TerminalLiteral ")"]);
  ("proposition", [Nonterminal "proposition_or"]);
  ("proposition_or", [Nonterminal "proposition_and"; Nonterminal "__proposition_or_star_0128"]);
  ("proposition_and", [Nonterminal "proposition_not"; Nonterminal "__proposition_and_star_0129"]);
  ("proposition_not", [TerminalLiteral "not"; Nonterminal "proposition_not"]);
  ("proposition_not", [Nonterminal "proposition_atom"]);
  ("proposition_atom", [Nonterminal "comparison_proposition"]);
  ("proposition_atom", [TerminalLiteral "("; Nonterminal "proposition"; TerminalLiteral ")"]);
  ("proposition_atom", [TerminalLiteral "true"]);
  ("proposition_atom", [TerminalLiteral "false"]);
  ("proposition_atom", [Nonterminal "claim_application"]);
  ("comparison_proposition", [Nonterminal "additive_expression"; Nonterminal "comparison_operator"; Nonterminal "additive_expression"]);
  ("comparison_operator", [TerminalLiteral "=="]);
  ("comparison_operator", [TerminalLiteral "!="]);
  ("comparison_operator", [TerminalLiteral "<="]);
  ("comparison_operator", [TerminalLiteral ">="]);
  ("comparison_operator", [TerminalLiteral "<"]);
  ("comparison_operator", [TerminalLiteral ">"]);
  ("claim_application", [Nonterminal "qualified_name"; TerminalLiteral "("; Nonterminal "__claim_application_opt_0131"; TerminalLiteral ")"]);
  ("__source_file_opt_0001", []);
  ("__source_file_opt_0001", [Nonterminal "module_decl"]);
  ("__source_file_star_0002", []);
  ("__source_file_star_0002", [Nonterminal "import_decl"; Nonterminal "__source_file_star_0002"]);
  ("__source_file_star_0003", []);
  ("__source_file_star_0003", [Nonterminal "top_level_decl"; Nonterminal "__source_file_star_0003"]);
  ("__import_decl_opt_0004", []);
  ("__import_decl_opt_0004", [TerminalLiteral "{"; Nonterminal "identifier_list"; TerminalLiteral "}"]);
  ("__top_level_decl_star_0005", []);
  ("__top_level_decl_star_0005", [Nonterminal "attribute"; Nonterminal "__top_level_decl_star_0005"]);
  ("__qualified_name_star_0006", []);
  ("__qualified_name_star_0006", [TerminalLiteral "."; Nonterminal "identifier"; Nonterminal "__qualified_name_star_0006"]);
  ("__identifier_list_star_0007", []);
  ("__identifier_list_star_0007", [TerminalLiteral ","; Nonterminal "identifier"; Nonterminal "__identifier_list_star_0007"]);
  ("__generic_params_star_0008", []);
  ("__generic_params_star_0008", [TerminalLiteral ","; Nonterminal "generic_param"; Nonterminal "__generic_params_star_0008"]);
  ("__generic_requirements_star_0009", []);
  ("__generic_requirements_star_0009", [Nonterminal "generic_requirement"; Nonterminal "__generic_requirements_star_0009"]);
  ("__term_params_star_0010", []);
  ("__term_params_star_0010", [TerminalLiteral ","; Nonterminal "term_param"; Nonterminal "__term_params_star_0010"]);
  ("__term_params_opt_0011", []);
  ("__term_params_opt_0011", [Nonterminal "term_param"; Nonterminal "__term_params_star_0010"]);
  ("__named_type_opt_0012", []);
  ("__named_type_opt_0012", [Nonterminal "static_arguments"]);
  ("__static_arguments_star_0013", []);
  ("__static_arguments_star_0013", [TerminalLiteral ","; Nonterminal "expression"; Nonterminal "__static_arguments_star_0013"]);
  ("__static_arguments_opt_0014", []);
  ("__static_arguments_opt_0014", [Nonterminal "expression"; Nonterminal "__static_arguments_star_0013"]);
  ("__term_arguments_star_0015", []);
  ("__term_arguments_star_0015", [TerminalLiteral ","; Nonterminal "expression"; Nonterminal "__term_arguments_star_0015"]);
  ("__term_arguments_opt_0016", []);
  ("__term_arguments_opt_0016", [Nonterminal "expression"; Nonterminal "__term_arguments_star_0015"]);
  ("__record_decl_opt_0017", []);
  ("__record_decl_opt_0017", [Nonterminal "generic_params"]);
  ("__record_decl_opt_0018", []);
  ("__record_decl_opt_0018", [Nonterminal "generic_requirements"]);
  ("__record_decl_star_0019", []);
  ("__record_decl_star_0019", [TerminalLiteral ","; Nonterminal "field_decl"; Nonterminal "__record_decl_star_0019"]);
  ("__record_decl_opt_0020", []);
  ("__record_decl_opt_0020", [TerminalLiteral ","]);
  ("__record_decl_opt_0021", []);
  ("__record_decl_opt_0021", [Nonterminal "field_decl"; Nonterminal "__record_decl_star_0019"; Nonterminal "__record_decl_opt_0020"]);
  ("__data_decl_opt_0022", []);
  ("__data_decl_opt_0022", [Nonterminal "generic_params"]);
  ("__data_decl_opt_0023", []);
  ("__data_decl_opt_0023", [Nonterminal "generic_requirements"]);
  ("__data_decl_star_0024", []);
  ("__data_decl_star_0024", [TerminalLiteral "|"; Nonterminal "variant_decl"; Nonterminal "__data_decl_star_0024"]);
  ("__variant_decl_opt_0025", []);
  ("__variant_decl_opt_0025", [Nonterminal "variant_payload"]);
  ("__variant_payload_star_0026", []);
  ("__variant_payload_star_0026", [TerminalLiteral ","; Nonterminal "field_decl"; Nonterminal "__variant_payload_star_0026"]);
  ("__variant_payload_opt_0027", []);
  ("__variant_payload_opt_0027", [TerminalLiteral ","]);
  ("__variant_payload_opt_0028", []);
  ("__variant_payload_opt_0028", [Nonterminal "field_decl"; Nonterminal "__variant_payload_star_0026"; Nonterminal "__variant_payload_opt_0027"]);
  ("__variant_payload_star_0029", []);
  ("__variant_payload_star_0029", [TerminalLiteral ","; Nonterminal "type_expression"; Nonterminal "__variant_payload_star_0029"]);
  ("__variant_payload_opt_0030", []);
  ("__variant_payload_opt_0030", [Nonterminal "type_expression"; Nonterminal "__variant_payload_star_0029"]);
  ("__type_alias_decl_opt_0031", []);
  ("__type_alias_decl_opt_0031", [Nonterminal "generic_params"]);
  ("__type_alias_decl_opt_0032", []);
  ("__type_alias_decl_opt_0032", [Nonterminal "generic_requirements"]);
  ("__claim_decl_opt_0033", []);
  ("__claim_decl_opt_0033", [Nonterminal "generic_params"]);
  ("__claim_decl_opt_0034", []);
  ("__claim_decl_opt_0034", [Nonterminal "generic_requirements"]);
  ("__claim_decl_opt_0035", []);
  ("__claim_decl_opt_0035", [Nonterminal "term_params"]);
  ("__claim_decl_opt_0036", []);
  ("__claim_decl_opt_0036", [TerminalLiteral "="; Nonterminal "proposition"]);
  ("__callable_contract_decl_opt_0037", []);
  ("__callable_contract_decl_opt_0037", [Nonterminal "generic_params"]);
  ("__callable_contract_decl_opt_0038", []);
  ("__callable_contract_decl_opt_0038", [Nonterminal "generic_requirements"]);
  ("__callable_contract_block_star_0039", []);
  ("__callable_contract_block_star_0039", [Nonterminal "callable_clause"; Nonterminal "__callable_contract_block_star_0039"]);
  ("__name_set_star_0040", []);
  ("__name_set_star_0040", [TerminalLiteral ","; Nonterminal "qualified_name"; Nonterminal "__name_set_star_0040"]);
  ("__name_set_opt_0041", []);
  ("__name_set_opt_0041", [Nonterminal "qualified_name"; Nonterminal "__name_set_star_0040"]);
  ("__type_set_star_0042", []);
  ("__type_set_star_0042", [TerminalLiteral ","; Nonterminal "type_expression"; Nonterminal "__type_set_star_0042"]);
  ("__type_set_opt_0043", []);
  ("__type_set_opt_0043", [Nonterminal "type_expression"; Nonterminal "__type_set_star_0042"]);
  ("__function_decl_opt_0044", []);
  ("__function_decl_opt_0044", [TerminalLiteral "recursive"]);
  ("__function_decl_opt_0045", []);
  ("__function_decl_opt_0045", [Nonterminal "generic_params"]);
  ("__function_decl_opt_0046", []);
  ("__function_decl_opt_0046", [Nonterminal "generic_requirements"]);
  ("__function_decl_opt_0047", []);
  ("__function_decl_opt_0047", [TerminalLiteral "->"; Nonterminal "type_expression"]);
  ("__provider_contract_decl_opt_0048", []);
  ("__provider_contract_decl_opt_0048", [Nonterminal "generic_params"]);
  ("__provider_contract_decl_opt_0049", []);
  ("__provider_contract_decl_opt_0049", [Nonterminal "generic_requirements"]);
  ("__provider_contract_decl_star_0050", []);
  ("__provider_contract_decl_star_0050", [Nonterminal "provider_contract_item"; Nonterminal "__provider_contract_decl_star_0050"]);
  ("__provider_implementation_decl_opt_0051", []);
  ("__provider_implementation_decl_opt_0051", [Nonterminal "generic_params"]);
  ("__provider_implementation_decl_opt_0052", []);
  ("__provider_implementation_decl_opt_0052", [Nonterminal "generic_requirements"]);
  ("__provider_implementation_decl_star_0053", []);
  ("__provider_implementation_decl_star_0053", [Nonterminal "provider_implementation_item"; Nonterminal "__provider_implementation_decl_star_0053"]);
  ("__opaque_provider_implementation_decl_opt_0054", []);
  ("__opaque_provider_implementation_decl_opt_0054", [Nonterminal "generic_params"]);
  ("__opaque_provider_implementation_decl_opt_0055", []);
  ("__opaque_provider_implementation_decl_opt_0055", [Nonterminal "generic_requirements"]);
  ("__protocol_decl_opt_0056", []);
  ("__protocol_decl_opt_0056", [Nonterminal "generic_params"]);
  ("__protocol_decl_opt_0057", []);
  ("__protocol_decl_opt_0057", [Nonterminal "generic_requirements"]);
  ("__session_expression_opt_0058", []);
  ("__session_expression_opt_0058", [TerminalLiteral "using"; Nonterminal "qualified_name"]);
  ("__session_expression_opt_0059", []);
  ("__session_expression_opt_0059", [TerminalLiteral "when"; Nonterminal "proposition"]);
  ("__session_expression_opt_0060", []);
  ("__session_expression_opt_0060", [TerminalLiteral "using"; Nonterminal "qualified_name"]);
  ("__session_expression_opt_0061", []);
  ("__session_expression_opt_0061", [TerminalLiteral "when"; Nonterminal "proposition"]);
  ("__session_expression_star_0062", []);
  ("__session_expression_star_0062", [TerminalLiteral "|"; Nonterminal "session_branch"; Nonterminal "__session_expression_star_0062"]);
  ("__session_expression_star_0063", []);
  ("__session_expression_star_0063", [TerminalLiteral "|"; Nonterminal "session_branch"; Nonterminal "__session_expression_star_0063"]);
  ("__session_branch_star_0064", []);
  ("__session_branch_star_0064", [TerminalLiteral ","; Nonterminal "term_param"; Nonterminal "__session_branch_star_0064"]);
  ("__session_branch_opt_0065", []);
  ("__session_branch_opt_0065", [TerminalLiteral "("; Nonterminal "__session_branch_opt_0066"; TerminalLiteral ")"]);
  ("__session_branch_opt_0066", []);
  ("__session_branch_opt_0066", [Nonterminal "term_param"; Nonterminal "__session_branch_star_0064"]);
  ("__session_branch_opt_0067", []);
  ("__session_branch_opt_0067", [TerminalLiteral "using"; Nonterminal "qualified_name"]);
  ("__session_branch_opt_0068", []);
  ("__session_branch_opt_0068", [TerminalLiteral "when"; Nonterminal "proposition"]);
  ("__capability_decl_opt_0069", []);
  ("__capability_decl_opt_0069", [Nonterminal "generic_params"]);
  ("__capability_decl_opt_0070", []);
  ("__capability_decl_opt_0070", [Nonterminal "generic_requirements"]);
  ("__capability_decl_star_0071", []);
  ("__capability_decl_star_0071", [Nonterminal "capability_item"; Nonterminal "__capability_decl_star_0071"]);
  ("__boundary_decl_opt_0072", []);
  ("__boundary_decl_opt_0072", [Nonterminal "generic_params"]);
  ("__boundary_decl_opt_0073", []);
  ("__boundary_decl_opt_0073", [Nonterminal "generic_requirements"]);
  ("__boundary_decl_star_0074", []);
  ("__boundary_decl_star_0074", [Nonterminal "boundary_item"; Nonterminal "__boundary_decl_star_0074"]);
  ("__architecture_decl_opt_0075", []);
  ("__architecture_decl_opt_0075", [Nonterminal "generic_params"]);
  ("__architecture_decl_opt_0076", []);
  ("__architecture_decl_opt_0076", [Nonterminal "generic_requirements"]);
  ("__architecture_decl_star_0077", []);
  ("__architecture_decl_star_0077", [Nonterminal "architecture_item"; Nonterminal "__architecture_decl_star_0077"]);
  ("__static_reference_opt_0078", []);
  ("__static_reference_opt_0078", [Nonterminal "static_arguments"]);
  ("__component_decl_opt_0079", []);
  ("__component_decl_opt_0079", [Nonterminal "generic_params"]);
  ("__component_decl_opt_0080", []);
  ("__component_decl_opt_0080", [Nonterminal "generic_requirements"]);
  ("__component_decl_opt_0081", []);
  ("__component_decl_opt_0081", [Nonterminal "term_params"]);
  ("__component_decl_opt_0082", []);
  ("__component_decl_opt_0082", [TerminalLiteral "provides"; Nonterminal "type_expression"]);
  ("__program_decl_opt_0083", []);
  ("__program_decl_opt_0083", [Nonterminal "program_block"]);
  ("__program_block_star_0084", []);
  ("__program_block_star_0084", [Nonterminal "program_item"; Nonterminal "__program_block_star_0084"]);
  ("__block_star_0085", []);
  ("__block_star_0085", [Nonterminal "statement"; Nonterminal "__block_star_0085"]);
  ("__tuple_pattern_star_0086", []);
  ("__tuple_pattern_star_0086", [TerminalLiteral ","; Nonterminal "pattern"; Nonterminal "__tuple_pattern_star_0086"]);
  ("__record_pattern_star_0087", []);
  ("__record_pattern_star_0087", [TerminalLiteral ","; Nonterminal "field_pattern"; Nonterminal "__record_pattern_star_0087"]);
  ("__record_pattern_opt_0088", []);
  ("__record_pattern_opt_0088", [TerminalLiteral ","]);
  ("__field_pattern_opt_0089", []);
  ("__field_pattern_opt_0089", [TerminalLiteral "="; Nonterminal "pattern"]);
  ("__expression_opt_0090", []);
  ("__expression_opt_0090", [TerminalLiteral "or"; Nonterminal "fallback"]);
  ("__additive_expression_star_0091", []);
  ("__additive_expression_star_0091", [TerminalLiteral "+"; Nonterminal "multiplicative_expression"; Nonterminal "__additive_expression_star_0091"]);
  ("__additive_expression_star_0091", [TerminalLiteral "-"; Nonterminal "multiplicative_expression"; Nonterminal "__additive_expression_star_0091"]);
  ("__multiplicative_expression_star_0092", []);
  ("__multiplicative_expression_star_0092", [TerminalLiteral "*"; Nonterminal "postfix_expression"; Nonterminal "__multiplicative_expression_star_0092"]);
  ("__postfix_expression_star_0093", []);
  ("__postfix_expression_star_0093", [TerminalLiteral "."; Nonterminal "identifier"; Nonterminal "__postfix_expression_star_0093"]);
  ("__name_expression_opt_0094", []);
  ("__name_expression_opt_0094", [Nonterminal "static_arguments"]);
  ("__name_expression_opt_0095", []);
  ("__name_expression_opt_0095", [Nonterminal "term_arguments"]);
  ("__construct_expression_star_0096", []);
  ("__construct_expression_star_0096", [TerminalLiteral ","; Nonterminal "field_assignment"; Nonterminal "__construct_expression_star_0096"]);
  ("__construct_expression_opt_0097", []);
  ("__construct_expression_opt_0097", [TerminalLiteral ","]);
  ("__construct_expression_opt_0098", []);
  ("__construct_expression_opt_0098", [Nonterminal "field_assignment"; Nonterminal "__construct_expression_star_0096"; Nonterminal "__construct_expression_opt_0097"]);
  ("__join_clause_star_0099", []);
  ("__join_clause_star_0099", [TerminalLiteral ","; Nonterminal "state_slot"; Nonterminal "__join_clause_star_0099"]);
  ("__join_clause_opt_0100", []);
  ("__join_clause_opt_0100", [Nonterminal "state_slot"; Nonterminal "__join_clause_star_0099"]);
  ("__if_expression_opt_0101", []);
  ("__if_expression_opt_0101", [Nonterminal "join_clause"]);
  ("__if_expression_opt_0102", []);
  ("__if_expression_opt_0102", [TerminalLiteral "else"; Nonterminal "block"]);
  ("__match_expression_opt_0103", []);
  ("__match_expression_opt_0103", [Nonterminal "join_clause"]);
  ("__match_expression_star_0104", []);
  ("__match_expression_star_0104", [Nonterminal "match_arm"; Nonterminal "__match_expression_star_0104"]);
  ("__case_pattern_star_0105", []);
  ("__case_pattern_star_0105", [TerminalLiteral ","; Nonterminal "identifier"; Nonterminal "__case_pattern_star_0105"]);
  ("__case_pattern_opt_0106", []);
  ("__case_pattern_opt_0106", [Nonterminal "identifier"; Nonterminal "__case_pattern_star_0105"]);
  ("__case_pattern_star_0107", []);
  ("__case_pattern_star_0107", [TerminalLiteral ","; Nonterminal "field_binder"; Nonterminal "__case_pattern_star_0107"]);
  ("__case_pattern_opt_0108", []);
  ("__case_pattern_opt_0108", [TerminalLiteral ","]);
  ("__case_pattern_opt_0109", []);
  ("__case_pattern_opt_0109", [Nonterminal "field_binder"; Nonterminal "__case_pattern_star_0107"; Nonterminal "__case_pattern_opt_0108"]);
  ("__case_pattern_opt_0110", []);
  ("__case_pattern_opt_0110", [TerminalLiteral "("; Nonterminal "__case_pattern_opt_0106"; TerminalLiteral ")"]);
  ("__case_pattern_opt_0110", [TerminalLiteral "{"; Nonterminal "__case_pattern_opt_0109"; TerminalLiteral "}"]);
  ("__field_binder_opt_0111", []);
  ("__field_binder_opt_0111", [TerminalLiteral "as"; Nonterminal "identifier"]);
  ("__decide_expression_star_0112", []);
  ("__decide_expression_star_0112", [Nonterminal "match_arm"; Nonterminal "__decide_expression_star_0112"]);
  ("__closure_expression_opt_0113", []);
  ("__closure_expression_opt_0113", [TerminalLiteral "captures"; TerminalLiteral "("; Nonterminal "__closure_expression_opt_0114"; TerminalLiteral ")"]);
  ("__closure_expression_opt_0114", []);
  ("__closure_expression_opt_0114", [Nonterminal "identifier_list"]);
  ("__loop_expression_star_0115", []);
  ("__loop_expression_star_0115", [TerminalLiteral ","; Nonterminal "state_binding"; Nonterminal "__loop_expression_star_0115"]);
  ("__loop_expression_opt_0116", []);
  ("__loop_expression_opt_0116", [Nonterminal "state_binding"; Nonterminal "__loop_expression_star_0115"]);
  ("__loop_expression_opt_0117", []);
  ("__loop_expression_opt_0117", [TerminalLiteral "state"; TerminalLiteral "("; Nonterminal "__loop_expression_opt_0116"; TerminalLiteral ")"]);
  ("__loop_expression_opt_0118", []);
  ("__loop_expression_opt_0118", [TerminalLiteral "invariant"; Nonterminal "proposition"]);
  ("__continue_expression_star_0119", []);
  ("__continue_expression_star_0119", [TerminalLiteral ","; Nonterminal "expression"; Nonterminal "__continue_expression_star_0119"]);
  ("__continue_expression_opt_0120", []);
  ("__continue_expression_opt_0120", [Nonterminal "expression"; Nonterminal "__continue_expression_star_0119"]);
  ("__continue_expression_opt_0121", []);
  ("__continue_expression_opt_0121", [TerminalLiteral "("; Nonterminal "__continue_expression_opt_0120"; TerminalLiteral ")"]);
  ("__break_expression_star_0122", []);
  ("__break_expression_star_0122", [TerminalLiteral ","; Nonterminal "expression"; Nonterminal "__break_expression_star_0122"]);
  ("__break_expression_opt_0123", []);
  ("__break_expression_opt_0123", [Nonterminal "expression"; Nonterminal "__break_expression_star_0122"]);
  ("__break_expression_opt_0124", []);
  ("__break_expression_opt_0124", [TerminalLiteral "("; Nonterminal "__break_expression_opt_0123"; TerminalLiteral ")"]);
  ("__receive_exact_expression_opt_0125", []);
  ("__receive_exact_expression_opt_0125", [TerminalLiteral "using"; Nonterminal "additive_expression"]);
  ("__validate_expression_opt_0126", []);
  ("__validate_expression_opt_0126", [TerminalLiteral "at"; Nonterminal "additive_expression"]);
  ("__select_expression_opt_0127", []);
  ("__select_expression_opt_0127", [TerminalLiteral "using"; Nonterminal "additive_expression"]);
  ("__branch_value_opt_0128", []);
  ("__branch_value_opt_0128", [Nonterminal "term_arguments"]);
  ("__failure_target_opt_0129", []);
  ("__failure_target_opt_0129", [Nonterminal "term_arguments"]);
  ("__parenthesized_expression_star_0130", []);
  ("__parenthesized_expression_star_0130", [TerminalLiteral ","; Nonterminal "expression"; Nonterminal "__parenthesized_expression_star_0130"]);
  ("__parenthesized_expression_opt_0131", []);
  ("__parenthesized_expression_opt_0131", [Nonterminal "expression"; Nonterminal "__parenthesized_expression_star_0130"]);
  ("__proposition_or_star_0132", []);
  ("__proposition_or_star_0132", [TerminalLiteral "or"; Nonterminal "proposition_and"; Nonterminal "__proposition_or_star_0132"]);
  ("__proposition_and_star_0133", []);
  ("__proposition_and_star_0133", [TerminalLiteral "and"; Nonterminal "proposition_not"; Nonterminal "__proposition_and_star_0133"]);
  ("__claim_application_star_0134", []);
  ("__claim_application_star_0134", [TerminalLiteral ","; Nonterminal "expression"; Nonterminal "__claim_application_star_0134"]);
  ("__claim_application_opt_0135", []);
  ("__claim_application_opt_0135", [Nonterminal "expression"; Nonterminal "__claim_application_star_0134"])
].

(* Option and repetition nodes in the EBNF are lowered to generated
   right-recursive nonterminals whose names begin with "__". *)
