{-# LANGUAGE OverloadedStrings #-}

module Main (main) where

import qualified Data.ByteString as ByteString
import qualified Data.Text as Text
import qualified Data.Text.Encoding as TextEncoding
import Phil.Assurance
import Phil.Core.Syntax (ObligationId (..))
import System.Environment (getArgs)
import System.Exit (exitFailure)
import System.IO (hPutStrLn, stderr)

main :: IO ()
main = do
  args <- getArgs
  case args of
    [sourcePath, compiledPath, outputPath] ->
      certifyWith phase1ProviderLineageCoreCertificationSpec
        sourcePath compiledPath outputPath
    _ -> do
      hPutStrLn stderr
        "usage: Phase1ProviderLineageCoreCertificationMain SOURCE.v COMPILED.vo OUTPUT.cert"
      exitFailure

phase1ProviderLineageCoreCertificationSpec :: RocqCertificationSpec
phase1ProviderLineageCoreCertificationSpec = RocqCertificationSpec
  { rocqSpecProfile = "phase1-provider-lineage-core"
  , rocqSpecObligation = ObligationId "PHIL-PROV-LINEAGE-CORE-001"
  , rocqSpecClaim =
      "Provider qualification claim identity is upstream of evidence-bundle identity and contextual admission identity: evidence must bind the exact claim revision, and admission must bind the exact claim revision, evidence revision, and required provider interface. Qualification dependency closure is the least grounding relation generated by independently accepted grounds and dependency inheritance, so circular qualification dependencies cannot self-endorse without an independent ground, while independently grounded dependency components close transitively."
  , rocqSpecKind = "Provider qualification lineage identity and grounded dependency closure"
  , rocqSpecOrigin =
      "src/Phil/Core/ProviderQualificationIdentity.hs; src/Phil/Core/ProviderQualificationDependency.hs; test/Phase1ProviderQualificationIdentityMain.hs; test/Phase1ProviderQualificationDependencyMain.hs; proof/Phil/Core/ProviderQualificationLineageCore.v"
  , rocqSpecScope =
      "Phase 1 PROV-011 qualification claim/evidence/admission identity separation plus PROV-012 independently grounded dependency closure"
  , rocqSpecRepresentation =
      "normalized exact claim/evidence/admission/interface/policy revision identities and an inductive least grounding/reachability relation over provider admission dependencies"
  , rocqSpecSubjects =
      [ "QualificationClaimIdentity"
      , "QualificationEvidenceIdentity"
      , "QualificationAdmissionIdentity"
      , "QualificationGrounded"
      , "QualificationReachable"
      , "QualificationDependencyClosure"
      ]
  , rocqSpecTheorems =
      [ "evidence_binding_requires_exact_claim_revision"
      , "admission_binding_requires_exact_claim_revision"
      , "admission_binding_requires_exact_evidence_revision"
      , "admission_binding_requires_exact_required_interface"
      , "replacing_evidence_preserves_claim_identity"
      , "distinct_evidence_revisions_do_not_change_claim_revision"
      , "admission_context_is_downstream_of_upstream_identity"
      , "direct_independent_ground_closes_one_admission"
      , "grounded_dependency_propagates_transitively"
      , "every_grounded_admission_has_independent_ground_leaf"
      , "cycles_cannot_self_endorse_without_independent_ground"
      , "grounded_cycle_closes_conditionally"
      , "direct_ground_requires_known_accepted_ground"
      , "root_is_reachable"
      , "dependency_reachability_is_transitive_one_step"
      , "closure_requires_every_reachable_admission_accepted"
      , "closure_requires_every_reachable_admission_grounded"
      , "rejected_reachable_admission_prevents_closure"
      , "multiple_independent_grounds_are_preserved_at_root"
      ]
  , rocqSpecSourceRef = ArtifactRef "proof/Phil/Core/ProviderQualificationLineageCore.v"
  , rocqSpecCompiledRef = ArtifactRef "proof/Phil/Core/ProviderQualificationLineageCore.vo"
  , rocqSpecCertificateRef = ArtifactRef "certificate:rocq:PHIL-PROV-LINEAGE-CORE-001:v1"
  , rocqSpecEvidenceId = EvidenceEntryId "evidence.PHIL-PROV-LINEAGE-CORE-001.rocq.v1"
  , rocqSpecResidualBoundary =
      "The theorem family certifies the normalized PROV-011/012 semantic core, not the concrete canonical SemanticForm serialization or revision digest construction. Reviewed correspondence from Text, Map/Set canonicalization, content-addressed revision construction, exact Haskell diagnostics, registry-key validation, and finite least-fixed-point iteration remains a trust boundary. Independent proof/runtime/external/assumption/TCB ground truth and validity scope remain explicit evidence facts rather than being proven here. PROV-013 cross-target semantic reuse, PROV-014 concrete admission applicability, provider replacement, ArchitectureRealization selection, Systems preservation, and target/backend realization remain separate obligations."
  }

certifyWith :: RocqCertificationSpec -> FilePath -> FilePath -> FilePath -> IO ()
certifyWith spec sourcePath compiledPath outputPath = do
  sourceBytes <- ByteString.readFile sourcePath
  compiledBytes <- ByteString.readFile compiledPath
  case certifyRocqProof spec sourceBytes compiledBytes of
    Left err -> do
      hPutStrLn stderr ("Rocq certification failed: " <> show err)
      exitFailure
    Right bundle -> do
      let certificate = rocqBundleCertificate bundle
          artifact = rocqBundleCertificateArtifact bundle
          ObligationId obligation = rocqCertificateObligation certificate
      ByteString.writeFile outputPath
        (TextEncoding.encodeUtf8 (renderRocqProofCertificate certificate))
      putStrLn
        ("certified " <> Text.unpack obligation <>
          " as ProofAssistantTheorem evidence")
      putStrLn
        ("certificate artifact: " <>
          Text.unpack (unArtifactRef (artifactReference artifact)))
      putStrLn
        ("certificate sha256: " <>
          Text.unpack (unDigest (artifactDigest artifact)))
